# Generated by Django 5.2.4 on 2025-08-14 19:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='bearing',
            field=models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='last_known_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Last known location of delivery agent', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='speed_kmh',
            field=models.FloatField(blank=True, help_text='Current speed in km/h', null=True),
        ),
    ]
